import { CheckCircle, Cpu, Database, QrCode, Upload, BadgeCheck, Layers, Code2, Shield, Star } from 'lucide-react';

function FeatureCard({ icon: Icon, title, desc }) {
  return (
    <div className="rounded-xl border border-white/10 bg-white/5 p-5 shadow-sm shadow-black/30">
      <div className="mb-3 inline-flex h-10 w-10 items-center justify-center rounded-lg bg-white/10">
        <Icon className="h-5 w-5 text-white" />
      </div>
      <h3 className="text-base font-semibold">{title}</h3>
      <p className="mt-1 text-sm text-white/70">{desc}</p>
    </div>
  );
}

export default function Features() {
  return (
    <section id="features" className="relative z-10 mx-auto max-w-7xl px-6 py-16">
      <div className="mx-auto max-w-2xl text-center">
        <p className="text-xs tracking-widest text-cyan-300/80">CORE IDEA</p>
        <h2 className="mt-2 text-3xl font-semibold md:text-4xl">Recognize, Verify, and Showcase Self-Learning</h2>
        <p className="mt-3 text-white/70">Source-agnostic verification, AI assessments, QR-certified credentials, and project validation — all powered by open-source tech.</p>
      </div>

      <div className="mt-10 grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-3">
        <FeatureCard icon={Layers} title="Source-Agnostic" desc="Learn from YouTube, blogs, books, podcasts, or MOOCs — Rushd respects independent education." />
        <FeatureCard icon={Cpu} title="AI-Powered Testing" desc="Adaptive MCQs, coding tasks, and reasoning checks generated by open-source LLMs." />
        <FeatureCard icon={QrCode} title="QR Verification" desc="Each certificate contains a unique QR code linking to a live authenticity page." />
        <FeatureCard icon={Upload} title="Project Uploads" desc="Attach files, images, or GitHub repos to prove real-world application." />
        <FeatureCard icon={BadgeCheck} title="Project Verification" desc="Peer/manual review now; AI-based evaluation and summaries next." />
        <FeatureCard icon={Star} title="Portfolio Dashboard" desc="A shareable resume of verified skills, certificates, and projects." />
      </div>

      <div className="mt-16 grid grid-cols-1 gap-6 rounded-2xl border border-white/10 bg-white/5 p-6 md:grid-cols-3">
        <div>
          <h3 className="flex items-center gap-2 text-lg font-semibold"><Shield className="h-5 w-5" /> Verification Layer</h3>
          <ul className="mt-3 space-y-2 text-sm text-white/70">
            <li className="flex items-start gap-2"><CheckCircle className="mt-0.5 h-4 w-4 text-emerald-400" /> QR codes via JS/Python libraries</li>
            <li className="flex items-start gap-2"><CheckCircle className="mt-0.5 h-4 w-4 text-emerald-400" /> Supabase stores certificate metadata</li>
            <li className="flex items-start gap-2"><CheckCircle className="mt-0.5 h-4 w-4 text-emerald-400" /> Public verification pages</li>
          </ul>
        </div>
        <div>
          <h3 className="flex items-center gap-2 text-lg font-semibold"><Database className="h-5 w-5" /> Backend & Infra</h3>
          <ul className="mt-3 space-y-2 text-sm text-white/70">
            <li className="flex items-start gap-2"><CheckCircle className="mt-0.5 h-4 w-4 text-emerald-400" /> Supabase: Postgres, Auth, Storage</li>
            <li className="flex items-start gap-2"><CheckCircle className="mt-0.5 h-4 w-4 text-emerald-400" /> Vercel frontend deployment</li>
            <li className="flex items-start gap-2"><CheckCircle className="mt-0.5 h-4 w-4 text-emerald-400" /> AI microservices on Render/Railway</li>
          </ul>
        </div>
        <div>
          <h3 className="flex items-center gap-2 text-lg font-semibold"><Code2 className="h-5 w-5" /> Open-Source LLMs</h3>
          <ul className="mt-3 space-y-2 text-sm text-white/70">
            <li className="flex items-start gap-2"><CheckCircle className="mt-0.5 h-4 w-4 text-emerald-400" /> Mistral, Llama 3, Phi-3-mini</li>
            <li className="flex items-start gap-2"><CheckCircle className="mt-0.5 h-4 w-4 text-emerald-400" /> Run via Hugging Face, Ollama, LocalAI</li>
            <li className="flex items-start gap-2"><CheckCircle className="mt-0.5 h-4 w-4 text-emerald-400" /> Offline-capable and cost-effective</li>
          </ul>
        </div>
      </div>

      <div id="pricing" className="mt-16">
        <div className="mx-auto max-w-2xl text-center">
          <p className="text-xs tracking-widest text-fuchsia-300/80">MONETIZATION</p>
          <h3 className="mt-2 text-2xl font-semibold">Simple, fair plans for learners and institutions</h3>
        </div>
        <div className="mt-8 grid grid-cols-1 gap-6 md:grid-cols-3">
          <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
            <p className="text-sm text-white/70">Free</p>
            <h4 className="mt-1 text-xl font-semibold">Starter</h4>
            <ul className="mt-4 space-y-2 text-sm text-white/70">
              <li>Up to 3 certificates/month</li>
              <li>Basic profile</li>
              <li>Source-agnostic verification</li>
            </ul>
          </div>
          <div className="rounded-2xl border border-cyan-400/30 bg-gradient-to-b from-cyan-400/10 to-white/5 p-6">
            <p className="text-sm text-cyan-300">Pro</p>
            <h4 className="mt-1 text-xl font-semibold">Unlimited</h4>
            <ul className="mt-4 space-y-2 text-sm text-white/80">
              <li>Unlimited certificates</li>
              <li>AI-based project analysis</li>
              <li>Learning insights & recommendations</li>
            </ul>
          </div>
          <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
            <p className="text-sm text-white/70">Institutional</p>
            <h4 className="mt-1 text-xl font-semibold">Teams</h4>
            <ul className="mt-4 space-y-2 text-sm text-white/70">
              <li>Bulk verification APIs</li>
              <li>White-labeled dashboards</li>
              <li>Admin & reporting</li>
            </ul>
          </div>
        </div>
      </div>

      <div className="mt-16 rounded-2xl border border-white/10 bg-gradient-to-b from-white/5 to-white/[0.02] p-6">
        <h3 className="flex items-center gap-2 text-lg font-semibold"><Star className="h-5 w-5 text-amber-300" /> Future Enhancements</h3>
        <ul className="mt-3 grid grid-cols-1 gap-3 text-sm text-white/80 md:grid-cols-2">
          <li>Gamified XP, streaks, and badges</li>
          <li>AI Learning Path Generator</li>
          <li>Peer review and endorsements</li>
          <li>AI Resume & portfolio PDF generator</li>
          <li>Global gallery of verified projects</li>
        </ul>
      </div>
    </section>
  );
}
